# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: send program
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: tubist.fedor@gmail.com
        password: ${{secrets.MAIL_PASSWORD}}
        subject: We've got a new version of ToyShop!
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        to: <tubist.fedor@gmail.com>
        from: Github bot <tubist.fedor@gmail.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: pom.xml
